#! /bin/bash

export Z=/afs/cern.ch/user/s/sboren/work/phdAna/jets/CMSSW_7_5_8_patch3/src/mcStudy
cd $Z
eval `scram runtime -sh`
cd - 

#cmsRun $Z/step0_GEN.py 
#cmsRun $Z/hepmc2edm.py file:$Z/InterMed_37p2/starlight$1.dat $Z/InterMed_6/GSoutput$1.root
#cmsRun $Z/step1_SIMv2.py file:$Z/InterMed_37p2/starlight$1.dat $Z/InterMed_37p2/simData_$1.root
#rm $Z/InterMed_37p2/GSoutput$1.root
#cmsRun $Z/step2_DIGI_L1_DIGI2RAW_HLT_PU.py file:$Z/InterMed_37p2/simData_$1.root $Z/InterMed_37p2/digiData_$1.root
#rm $Z/InterMed_37p2/simData_$1.root
#cmsRun $Z/step3_RAW2DIGI_L1Reco_RECO.py file:$Z/InterMed_37p2/digiData_$1.root $Z/InterMed_37p2/recoData_$1.root
#rm $Z/InterMed_37p2/digiData_$1.root
#cmsRun $Z/step4_hiForest.py file:$Z/InterMed_37p2/recoData_$1.root $Z/TREE_37p2/hiForest_$1.root
#rm $Z/InterMed_37p2/recoData_$1.root
#cmsRun $Z/readHepMC_cfg.py file:$Z/hepmc/PbPb2015_jet_hepmc/rapgap_$1.dat $Z/aod/PbPb2015_jet_aod/aodMC$1.root
cmsRun $Z/runForestAOD_pp_MC_75X.py file:$Z/aod/PbPb2015_jet_aod/aodMC$1.root $Z/tree/PbPb2015_jet_tree/hiforest$1.root
#rm $Z/aod/PbPb2015_jet_aod/aodMC$1.root
